[build]
builder = "dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyMaxRetries = 3

[[services]]
name = "ai-chat-app"

[services.variables]
PORT = "5000"
HOST = "0.0.0.0"
FLASK_DEBUG = "false"
